name: chpi
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=21.2.0=pyhd3eb1b0_0
  - ca-certificates=2021.5.25=h06a4308_1
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - more-itertools=8.8.0=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - packaging=20.9=pyhd3eb1b0_0
  - pip=21.1.1=py36h06a4308_0
  - pluggy=0.13.1=py36h06a4308_0
  - py=1.10.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pytest=6.2.3=py36h06a4308_2
  - python=3.6.13=hdb3f193_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py36h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - aiohttp==3.7.4.post0
    - anyio==3.1.0
    - argon2-cffi==20.1.0
    - astroid==2.5.7
    - async-generator==1.10
    - async-timeout==3.0.1
    - backcall==0.2.0
    - bleach==3.3.0
    - cdbw==0.2
    - certifi==2020.12.5
    - cffi==1.14.5
    - chardet==4.0.0
    - cloudpickle==2.0.0
    - configspace==0.4.19
    - contextvars==2.4
    - cycler==0.10.0
    - cython==0.29.23
    - dataclasses==0.8
    - decorator==4.4.2
    - defusedxml==0.7.1
    - entrypoints==0.3
    - fanova==2.0.19
    - flake8==3.9.2
    - future==0.18.2
    - hyperopt==0.2.7
    - idna
    - idna-ssl==1.1.0
    - immutables==0.15
    - importlib-metadata==4.5.0
    - ipykernel==5.5.5
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - isort==5.8.0
    - jedi==0.17.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyter-server==1.8.0
    - jupyter-server-proxy==3.0.2
    - jupyter-vscode-server==0.0.10
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - lazy-object-proxy==1.6.0
    - liac-arff==2.5.0
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - mccabe==0.6.1
    - mistune==0.8.4
    - multidict==5.1.0
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - notebook==6.4.0
    - numpy==1.19.5
    - pandas==1.1.5
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.2.0
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.18
    - ptyprocess==0.7.0
    - py4j==0.10.9.3
    - pycodestyle
    - pycparser==2.20
    - pyflakes==2.3.1
    - pygments==2.9.0
    - pylint==2.8.2
    - pyrfr==0.8.2
    - pyrsistent==0.17.3
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pyzmq==20.0.0
    - qtconsole==5.1.0
    - qtpy==1.9.0
    - s-dbw==0.4.0
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - seaborn==0.11.1
    - send2trash==1.5.0
    - simpervisor==0.4
    - six==1.16.0
    - sniffio==1.2.0
    - terminado==0.9.4
    - testpath==0.5.0
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==4.3.3
    - typed-ast==1.4.3
    - typing-extensions==3.10.0.0
    - validclust==0.1.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - yarl==1.6.3
prefix: /home/javad/miniconda3/envs/chpi
